baseURL = 'http://adriandanao.com/'
languageCode = 'en-us'
title = 'Adrian Danao-Schroeder'
theme = 'paper'


[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  github = 'andanao'                   # github.com/YOUR_GITHUB_ID
  linkedin = 'adrian-danao-schroeder'  # linkedin.com/in/YOUR_LINKEDIN_ID
  rss = true                           # show rss icon

  # home page profile
  # avatar = 'GRAVATAR_EMAIL'                 # gravatar email or image url
  name = 'Adrian Danao-Schroeder'
  bio = 'YOUR_BIO'


  # misc
  disableHLJS = true                        # disable highlight.js
  monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)
  math = true                               # enable KaTex math typesetting globally
  comments = false                          # disable comments for a specific page
